name: PHP Composer

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install composer
        run: composer install

      - name: Run phpstan
        run: ./vendor/bin/phpstan analyse src --level 4