name: PHP Composer

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
       path: vendor
       key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
       restore-keys: |
         ${{ runner.os }}-php-

    - name: Install composer
      run: composer install

    - name: Run phpstan
      run: ./vendor/bin/phpstan analyse src --level 4

    - name: Run tests
      run: composer run-script test